version: 1.0.{build}

install:
  - choco install -y virtualbox --version 4.3.34
  - choco install -y docker-machine

build: off

before_test:
  - docker-machine.exe create -d virtualbox dev
  - docker-machine.exe env dev
