version: 1.0.{build}

install:
  - choco install -y mingw
  - choco install -y virtualbox
  - choco install -y docker-machine

build: off

before_test:
  - docker-machine.exe create -d virtualbox dev
  - docker-machine.exe env dev
